version: "3.7"
services:
  product_service:
    build: ./product-service
    restart: always
    ports:
      - 8080:8080
    networks:
      - organization-mysql
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/development?allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb

    volumes:
      - .m2:/root/.m2


  auth_service:
    build: ./auth-service
    restart: always
    ports:
      - 8081:8081
    networks:
      - organization-redis
    depends_on:
      - redis

    volumes:
      - .m2:/root/.m2

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - organization-redis

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    networks:
      - organization-mysql  
    environment:
      MYSQL_DATABASE: development
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
networks:
  organization-mysql:
  organization-redis:

volumes:
  mysql_data:
