server.servlet.context-path=/userservice
server.port=8082

spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=simplemicroservice

# Oauth2
oauth2.clientId=client1234
oauth2.clientSecret=Ri~V!NO4B4!IWg-!

# base url
url.authorizationManagementService=http://localhost:8081/authservice

# authorization management service
url.generateToken=${url.authorizationManagementService}/oauth/token
url.revokeToken=${url.authorizationManagementService}/revoketoken
url.validateToken=${url.authorizationManagementService}/validatetoken
